/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevRouteImport } from './routes/dev'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as EventsRouteRouteImport } from './routes/events/route'
import { Route as AccountsRouteRouteImport } from './routes/accounts/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as AccountsIndexRouteImport } from './routes/accounts/index'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as AccountsAccountIdRouteRouteImport } from './routes/accounts/$accountId/route'
import { Route as AccountsAccountIdIndexRouteImport } from './routes/accounts/$accountId/index'
import { Route as AccountsAccountIdInstrumentsRouteRouteImport } from './routes/accounts/$accountId/instruments/route'
import { Route as AccountsAccountIdImportsRouteRouteImport } from './routes/accounts/$accountId/imports/route'
import { Route as AccountsAccountIdEventsRouteRouteImport } from './routes/accounts/$accountId/events/route'
import { Route as AccountsAccountIdInstrumentsIndexRouteImport } from './routes/accounts/$accountId/instruments/index'
import { Route as AccountsAccountIdImportsIndexRouteImport } from './routes/accounts/$accountId/imports/index'
import { Route as AccountsAccountIdEventsIndexRouteImport } from './routes/accounts/$accountId/events/index'
import { Route as AccountsAccountIdInstrumentsInstrumentIdRouteImport } from './routes/accounts/$accountId/instruments/$instrumentId'
import { Route as AccountsAccountIdImportsImportIdRouteImport } from './routes/accounts/$accountId/imports/$importId'
import { Route as AccountsAccountIdEventsEventIdRouteImport } from './routes/accounts/$accountId/events/$eventId'

const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRouteRoute = EventsRouteRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRouteRoute = AccountsRouteRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRouteRoute,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountsRouteRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRouteRoute,
} as any)
const AccountsAccountIdRouteRoute = AccountsAccountIdRouteRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => AccountsRouteRoute,
} as any)
const AccountsAccountIdIndexRoute = AccountsAccountIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountsAccountIdRouteRoute,
} as any)
const AccountsAccountIdInstrumentsRouteRoute =
  AccountsAccountIdInstrumentsRouteRouteImport.update({
    id: '/instruments',
    path: '/instruments',
    getParentRoute: () => AccountsAccountIdRouteRoute,
  } as any)
const AccountsAccountIdImportsRouteRoute =
  AccountsAccountIdImportsRouteRouteImport.update({
    id: '/imports',
    path: '/imports',
    getParentRoute: () => AccountsAccountIdRouteRoute,
  } as any)
const AccountsAccountIdEventsRouteRoute =
  AccountsAccountIdEventsRouteRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AccountsAccountIdRouteRoute,
  } as any)
const AccountsAccountIdInstrumentsIndexRoute =
  AccountsAccountIdInstrumentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AccountsAccountIdInstrumentsRouteRoute,
  } as any)
const AccountsAccountIdImportsIndexRoute =
  AccountsAccountIdImportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AccountsAccountIdImportsRouteRoute,
  } as any)
const AccountsAccountIdEventsIndexRoute =
  AccountsAccountIdEventsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AccountsAccountIdEventsRouteRoute,
  } as any)
const AccountsAccountIdInstrumentsInstrumentIdRoute =
  AccountsAccountIdInstrumentsInstrumentIdRouteImport.update({
    id: '/$instrumentId',
    path: '/$instrumentId',
    getParentRoute: () => AccountsAccountIdInstrumentsRouteRoute,
  } as any)
const AccountsAccountIdImportsImportIdRoute =
  AccountsAccountIdImportsImportIdRouteImport.update({
    id: '/$importId',
    path: '/$importId',
    getParentRoute: () => AccountsAccountIdImportsRouteRoute,
  } as any)
const AccountsAccountIdEventsEventIdRoute =
  AccountsAccountIdEventsEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => AccountsAccountIdEventsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteRouteWithChildren
  '/events': typeof EventsRouteRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/dev': typeof DevRoute
  '/accounts/$accountId': typeof AccountsAccountIdRouteRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRoute
  '/accounts/': typeof AccountsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/accounts/$accountId/events': typeof AccountsAccountIdEventsRouteRouteWithChildren
  '/accounts/$accountId/imports': typeof AccountsAccountIdImportsRouteRouteWithChildren
  '/accounts/$accountId/instruments': typeof AccountsAccountIdInstrumentsRouteRouteWithChildren
  '/accounts/$accountId/': typeof AccountsAccountIdIndexRoute
  '/accounts/$accountId/events/$eventId': typeof AccountsAccountIdEventsEventIdRoute
  '/accounts/$accountId/imports/$importId': typeof AccountsAccountIdImportsImportIdRoute
  '/accounts/$accountId/instruments/$instrumentId': typeof AccountsAccountIdInstrumentsInstrumentIdRoute
  '/accounts/$accountId/events/': typeof AccountsAccountIdEventsIndexRoute
  '/accounts/$accountId/imports/': typeof AccountsAccountIdImportsIndexRoute
  '/accounts/$accountId/instruments/': typeof AccountsAccountIdInstrumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/dev': typeof DevRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/accounts': typeof AccountsIndexRoute
  '/events': typeof EventsIndexRoute
  '/accounts/$accountId': typeof AccountsAccountIdIndexRoute
  '/accounts/$accountId/events/$eventId': typeof AccountsAccountIdEventsEventIdRoute
  '/accounts/$accountId/imports/$importId': typeof AccountsAccountIdImportsImportIdRoute
  '/accounts/$accountId/instruments/$instrumentId': typeof AccountsAccountIdInstrumentsInstrumentIdRoute
  '/accounts/$accountId/events': typeof AccountsAccountIdEventsIndexRoute
  '/accounts/$accountId/imports': typeof AccountsAccountIdImportsIndexRoute
  '/accounts/$accountId/instruments': typeof AccountsAccountIdInstrumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteRouteWithChildren
  '/events': typeof EventsRouteRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/dev': typeof DevRoute
  '/accounts/$accountId': typeof AccountsAccountIdRouteRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRoute
  '/accounts/': typeof AccountsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/accounts/$accountId/events': typeof AccountsAccountIdEventsRouteRouteWithChildren
  '/accounts/$accountId/imports': typeof AccountsAccountIdImportsRouteRouteWithChildren
  '/accounts/$accountId/instruments': typeof AccountsAccountIdInstrumentsRouteRouteWithChildren
  '/accounts/$accountId/': typeof AccountsAccountIdIndexRoute
  '/accounts/$accountId/events/$eventId': typeof AccountsAccountIdEventsEventIdRoute
  '/accounts/$accountId/imports/$importId': typeof AccountsAccountIdImportsImportIdRoute
  '/accounts/$accountId/instruments/$instrumentId': typeof AccountsAccountIdInstrumentsInstrumentIdRoute
  '/accounts/$accountId/events/': typeof AccountsAccountIdEventsIndexRoute
  '/accounts/$accountId/imports/': typeof AccountsAccountIdImportsIndexRoute
  '/accounts/$accountId/instruments/': typeof AccountsAccountIdInstrumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/events'
    | '/categories'
    | '/dev'
    | '/accounts/$accountId'
    | '/events/$eventId'
    | '/accounts/'
    | '/events/'
    | '/accounts/$accountId/events'
    | '/accounts/$accountId/imports'
    | '/accounts/$accountId/instruments'
    | '/accounts/$accountId/'
    | '/accounts/$accountId/events/$eventId'
    | '/accounts/$accountId/imports/$importId'
    | '/accounts/$accountId/instruments/$instrumentId'
    | '/accounts/$accountId/events/'
    | '/accounts/$accountId/imports/'
    | '/accounts/$accountId/instruments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/dev'
    | '/events/$eventId'
    | '/accounts'
    | '/events'
    | '/accounts/$accountId'
    | '/accounts/$accountId/events/$eventId'
    | '/accounts/$accountId/imports/$importId'
    | '/accounts/$accountId/instruments/$instrumentId'
    | '/accounts/$accountId/events'
    | '/accounts/$accountId/imports'
    | '/accounts/$accountId/instruments'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/events'
    | '/categories'
    | '/dev'
    | '/accounts/$accountId'
    | '/events/$eventId'
    | '/accounts/'
    | '/events/'
    | '/accounts/$accountId/events'
    | '/accounts/$accountId/imports'
    | '/accounts/$accountId/instruments'
    | '/accounts/$accountId/'
    | '/accounts/$accountId/events/$eventId'
    | '/accounts/$accountId/imports/$importId'
    | '/accounts/$accountId/instruments/$instrumentId'
    | '/accounts/$accountId/events/'
    | '/accounts/$accountId/imports/'
    | '/accounts/$accountId/instruments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRouteRoute: typeof AccountsRouteRouteWithChildren
  EventsRouteRoute: typeof EventsRouteRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  DevRoute: typeof DevRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRouteRoute
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof AccountsRouteRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRouteRoute
    }
    '/accounts/$accountId': {
      id: '/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AccountsAccountIdRouteRouteImport
      parentRoute: typeof AccountsRouteRoute
    }
    '/accounts/$accountId/': {
      id: '/accounts/$accountId/'
      path: '/'
      fullPath: '/accounts/$accountId/'
      preLoaderRoute: typeof AccountsAccountIdIndexRouteImport
      parentRoute: typeof AccountsAccountIdRouteRoute
    }
    '/accounts/$accountId/instruments': {
      id: '/accounts/$accountId/instruments'
      path: '/instruments'
      fullPath: '/accounts/$accountId/instruments'
      preLoaderRoute: typeof AccountsAccountIdInstrumentsRouteRouteImport
      parentRoute: typeof AccountsAccountIdRouteRoute
    }
    '/accounts/$accountId/imports': {
      id: '/accounts/$accountId/imports'
      path: '/imports'
      fullPath: '/accounts/$accountId/imports'
      preLoaderRoute: typeof AccountsAccountIdImportsRouteRouteImport
      parentRoute: typeof AccountsAccountIdRouteRoute
    }
    '/accounts/$accountId/events': {
      id: '/accounts/$accountId/events'
      path: '/events'
      fullPath: '/accounts/$accountId/events'
      preLoaderRoute: typeof AccountsAccountIdEventsRouteRouteImport
      parentRoute: typeof AccountsAccountIdRouteRoute
    }
    '/accounts/$accountId/instruments/': {
      id: '/accounts/$accountId/instruments/'
      path: '/'
      fullPath: '/accounts/$accountId/instruments/'
      preLoaderRoute: typeof AccountsAccountIdInstrumentsIndexRouteImport
      parentRoute: typeof AccountsAccountIdInstrumentsRouteRoute
    }
    '/accounts/$accountId/imports/': {
      id: '/accounts/$accountId/imports/'
      path: '/'
      fullPath: '/accounts/$accountId/imports/'
      preLoaderRoute: typeof AccountsAccountIdImportsIndexRouteImport
      parentRoute: typeof AccountsAccountIdImportsRouteRoute
    }
    '/accounts/$accountId/events/': {
      id: '/accounts/$accountId/events/'
      path: '/'
      fullPath: '/accounts/$accountId/events/'
      preLoaderRoute: typeof AccountsAccountIdEventsIndexRouteImport
      parentRoute: typeof AccountsAccountIdEventsRouteRoute
    }
    '/accounts/$accountId/instruments/$instrumentId': {
      id: '/accounts/$accountId/instruments/$instrumentId'
      path: '/$instrumentId'
      fullPath: '/accounts/$accountId/instruments/$instrumentId'
      preLoaderRoute: typeof AccountsAccountIdInstrumentsInstrumentIdRouteImport
      parentRoute: typeof AccountsAccountIdInstrumentsRouteRoute
    }
    '/accounts/$accountId/imports/$importId': {
      id: '/accounts/$accountId/imports/$importId'
      path: '/$importId'
      fullPath: '/accounts/$accountId/imports/$importId'
      preLoaderRoute: typeof AccountsAccountIdImportsImportIdRouteImport
      parentRoute: typeof AccountsAccountIdImportsRouteRoute
    }
    '/accounts/$accountId/events/$eventId': {
      id: '/accounts/$accountId/events/$eventId'
      path: '/$eventId'
      fullPath: '/accounts/$accountId/events/$eventId'
      preLoaderRoute: typeof AccountsAccountIdEventsEventIdRouteImport
      parentRoute: typeof AccountsAccountIdEventsRouteRoute
    }
  }
}

interface AccountsAccountIdEventsRouteRouteChildren {
  AccountsAccountIdEventsEventIdRoute: typeof AccountsAccountIdEventsEventIdRoute
  AccountsAccountIdEventsIndexRoute: typeof AccountsAccountIdEventsIndexRoute
}

const AccountsAccountIdEventsRouteRouteChildren: AccountsAccountIdEventsRouteRouteChildren =
  {
    AccountsAccountIdEventsEventIdRoute: AccountsAccountIdEventsEventIdRoute,
    AccountsAccountIdEventsIndexRoute: AccountsAccountIdEventsIndexRoute,
  }

const AccountsAccountIdEventsRouteRouteWithChildren =
  AccountsAccountIdEventsRouteRoute._addFileChildren(
    AccountsAccountIdEventsRouteRouteChildren,
  )

interface AccountsAccountIdImportsRouteRouteChildren {
  AccountsAccountIdImportsImportIdRoute: typeof AccountsAccountIdImportsImportIdRoute
  AccountsAccountIdImportsIndexRoute: typeof AccountsAccountIdImportsIndexRoute
}

const AccountsAccountIdImportsRouteRouteChildren: AccountsAccountIdImportsRouteRouteChildren =
  {
    AccountsAccountIdImportsImportIdRoute:
      AccountsAccountIdImportsImportIdRoute,
    AccountsAccountIdImportsIndexRoute: AccountsAccountIdImportsIndexRoute,
  }

const AccountsAccountIdImportsRouteRouteWithChildren =
  AccountsAccountIdImportsRouteRoute._addFileChildren(
    AccountsAccountIdImportsRouteRouteChildren,
  )

interface AccountsAccountIdInstrumentsRouteRouteChildren {
  AccountsAccountIdInstrumentsInstrumentIdRoute: typeof AccountsAccountIdInstrumentsInstrumentIdRoute
  AccountsAccountIdInstrumentsIndexRoute: typeof AccountsAccountIdInstrumentsIndexRoute
}

const AccountsAccountIdInstrumentsRouteRouteChildren: AccountsAccountIdInstrumentsRouteRouteChildren =
  {
    AccountsAccountIdInstrumentsInstrumentIdRoute:
      AccountsAccountIdInstrumentsInstrumentIdRoute,
    AccountsAccountIdInstrumentsIndexRoute:
      AccountsAccountIdInstrumentsIndexRoute,
  }

const AccountsAccountIdInstrumentsRouteRouteWithChildren =
  AccountsAccountIdInstrumentsRouteRoute._addFileChildren(
    AccountsAccountIdInstrumentsRouteRouteChildren,
  )

interface AccountsAccountIdRouteRouteChildren {
  AccountsAccountIdEventsRouteRoute: typeof AccountsAccountIdEventsRouteRouteWithChildren
  AccountsAccountIdImportsRouteRoute: typeof AccountsAccountIdImportsRouteRouteWithChildren
  AccountsAccountIdInstrumentsRouteRoute: typeof AccountsAccountIdInstrumentsRouteRouteWithChildren
  AccountsAccountIdIndexRoute: typeof AccountsAccountIdIndexRoute
}

const AccountsAccountIdRouteRouteChildren: AccountsAccountIdRouteRouteChildren =
  {
    AccountsAccountIdEventsRouteRoute:
      AccountsAccountIdEventsRouteRouteWithChildren,
    AccountsAccountIdImportsRouteRoute:
      AccountsAccountIdImportsRouteRouteWithChildren,
    AccountsAccountIdInstrumentsRouteRoute:
      AccountsAccountIdInstrumentsRouteRouteWithChildren,
    AccountsAccountIdIndexRoute: AccountsAccountIdIndexRoute,
  }

const AccountsAccountIdRouteRouteWithChildren =
  AccountsAccountIdRouteRoute._addFileChildren(
    AccountsAccountIdRouteRouteChildren,
  )

interface AccountsRouteRouteChildren {
  AccountsAccountIdRouteRoute: typeof AccountsAccountIdRouteRouteWithChildren
  AccountsIndexRoute: typeof AccountsIndexRoute
}

const AccountsRouteRouteChildren: AccountsRouteRouteChildren = {
  AccountsAccountIdRouteRoute: AccountsAccountIdRouteRouteWithChildren,
  AccountsIndexRoute: AccountsIndexRoute,
}

const AccountsRouteRouteWithChildren = AccountsRouteRoute._addFileChildren(
  AccountsRouteRouteChildren,
)

interface EventsRouteRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteRouteChildren: EventsRouteRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteRouteWithChildren = EventsRouteRoute._addFileChildren(
  EventsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRouteRoute: AccountsRouteRouteWithChildren,
  EventsRouteRoute: EventsRouteRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  DevRoute: DevRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
