/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevRouteImport } from './routes/dev'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as ImportsRouteRouteImport } from './routes/imports.route'
import { Route as EventsRouteRouteImport } from './routes/events.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImportsIndexRouteImport } from './routes/imports.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as ImportsIdRouteImport } from './routes/imports.$id'
import { Route as EventsIdRouteImport } from './routes/events.$id'

const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsRouteRoute = ImportsRouteRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRouteRoute = EventsRouteRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsIndexRoute = ImportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImportsRouteRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRouteRoute,
} as any)
const ImportsIdRoute = ImportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ImportsRouteRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRouteRouteWithChildren
  '/imports': typeof ImportsRouteRouteWithChildren
  '/accounts': typeof AccountsRoute
  '/categories': typeof CategoriesRoute
  '/dev': typeof DevRoute
  '/events/$id': typeof EventsIdRoute
  '/imports/$id': typeof ImportsIdRoute
  '/events/': typeof EventsIndexRoute
  '/imports/': typeof ImportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/categories': typeof CategoriesRoute
  '/dev': typeof DevRoute
  '/events/$id': typeof EventsIdRoute
  '/imports/$id': typeof ImportsIdRoute
  '/events': typeof EventsIndexRoute
  '/imports': typeof ImportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRouteRouteWithChildren
  '/imports': typeof ImportsRouteRouteWithChildren
  '/accounts': typeof AccountsRoute
  '/categories': typeof CategoriesRoute
  '/dev': typeof DevRoute
  '/events/$id': typeof EventsIdRoute
  '/imports/$id': typeof ImportsIdRoute
  '/events/': typeof EventsIndexRoute
  '/imports/': typeof ImportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/imports'
    | '/accounts'
    | '/categories'
    | '/dev'
    | '/events/$id'
    | '/imports/$id'
    | '/events/'
    | '/imports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/categories'
    | '/dev'
    | '/events/$id'
    | '/imports/$id'
    | '/events'
    | '/imports'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/imports'
    | '/accounts'
    | '/categories'
    | '/dev'
    | '/events/$id'
    | '/imports/$id'
    | '/events/'
    | '/imports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRouteRoute: typeof EventsRouteRouteWithChildren
  ImportsRouteRoute: typeof ImportsRouteRouteWithChildren
  AccountsRoute: typeof AccountsRoute
  CategoriesRoute: typeof CategoriesRoute
  DevRoute: typeof DevRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports': {
      id: '/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof ImportsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports/': {
      id: '/imports/'
      path: '/'
      fullPath: '/imports/'
      preLoaderRoute: typeof ImportsIndexRouteImport
      parentRoute: typeof ImportsRouteRoute
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRouteRoute
    }
    '/imports/$id': {
      id: '/imports/$id'
      path: '/$id'
      fullPath: '/imports/$id'
      preLoaderRoute: typeof ImportsIdRouteImport
      parentRoute: typeof ImportsRouteRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRouteRoute
    }
  }
}

interface EventsRouteRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteRouteChildren: EventsRouteRouteChildren = {
  EventsIdRoute: EventsIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteRouteWithChildren = EventsRouteRoute._addFileChildren(
  EventsRouteRouteChildren,
)

interface ImportsRouteRouteChildren {
  ImportsIdRoute: typeof ImportsIdRoute
  ImportsIndexRoute: typeof ImportsIndexRoute
}

const ImportsRouteRouteChildren: ImportsRouteRouteChildren = {
  ImportsIdRoute: ImportsIdRoute,
  ImportsIndexRoute: ImportsIndexRoute,
}

const ImportsRouteRouteWithChildren = ImportsRouteRoute._addFileChildren(
  ImportsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRouteRoute: EventsRouteRouteWithChildren,
  ImportsRouteRoute: ImportsRouteRouteWithChildren,
  AccountsRoute: AccountsRoute,
  CategoriesRoute: CategoriesRoute,
  DevRoute: DevRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
